name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install fontconfig
      run: sudo apt-get update && sudo apt-get install -y fontconfig libfontconfig1
    - uses: actions/checkout@v4
    - name: Build the Docker image AnalysisOfAspose
      run: |
        TAG=$(date +%s)
        docker build . --file AnalysisOfAspose/Dockerfile --tag analysis_of_aspose:$TAG
        echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
    - name: Create data directory with permissions
      run: |
        sudo mkdir -p /data
        sudo chmod 777 /data
    - name: Run console application
      run: docker run --rm -v "/data:/data" analysis_of_aspose:${{ env.IMAGE_TAG }} .